### ISSUE TITLE
No way of contacting you - Viridithas is in tourney being broadcast live

### ISSUE THREAD

**Issue by GrahamCCRL** [cosmobobak/viridithas-chess#17]
95TH AMATEUR SERIES (Division 8 )

Intel i7 Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
ICCF-Pre2022HQ.cgb book
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 44 rounds
All engines 64-bit where available

The top engine will gain automatic promotion. Any other changes of division will be at my discretion and may not necessarily involve playoff matches.

Participants

Myrddin 0.89 64-bit (relegated)
Raven 1.20 64-bit (relegated)
Tantabus 2.0.0 64-bit (relegated)
paulchen332 0.1.1 64-bit (relegated)
Admete 1.5.0 64-bit (relegated)
StockNemo 4.0.0.1 64-bit (new)
FoxSEE 8.2.0 64-bit
Viridithas 2.4.1 64-bit (new)
CT800 1.43 64-bit (relegated)
Prophet 4.2 64-bit
Waxman 2020
Barbarossa 0.6.0 64-bit

Games and standings will be available after every six rounds from the following link:
http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=14470

Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16094

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your computer, you can watch the games live move by move. You'll also be able to chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959
Host - GrahamCCRL.dyndns.org Port - 16094

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by cosmobobak** [comment]
oh awesome! i can be found on discord at `affinelytyped#8344`, for future reference.

**Comment by GrahamCCRL** [comment]
Okay. Thanks. :-)

**Comment by GrahamCCRL** [comment]
*WISDOM OF THE CENTAUR*

Intel i7 Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
SuperGM2020.cgb book
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 44 rounds
All engines 64-bit 1CPU (where available)


*Participants*

Chiron 5 64-bit
DanaSah 9.00 64-bit
Andscacs 0.95 64-bit
RukChess 3.0 64-bit
LG Evolution 3.15.4 64-bit
Dark Toga 1.1 64-bit
Winter 1.0 64-bit
Orion 0.9 64-bit
NirvanaChess 2.5 64-bit
Demolito 2021-10-04 64-bit
Vajolet2 2.8 64-bit
Viridithas 5.1.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16093

**Comment by cosmobobak** [comment]
neat!

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Fri, Dec 23, 2022 at 10:06 AM
Subject: 98th Amateur Series Division 4 underway - hope you'll visit the
live broadcast
To: ***@***.***>, ***@***.***>, David <
***@***.***>, Lucas Braesch ***@***.***>, Tom Hyer
***@***.***>, Edsel Apostol ***@***.***>, Vincent Yu <
***@***.***>, ***@***.***>, <
***@***.***>


*98TH AMATEUR SERIES (Division 4)*

Intel i7 Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
HarrySchnapp.cgb book (limited to 8 moves)
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 44 rounds
All engines 64-bit 1CPU (where available)

*The top engine will gain automatic promotion and the bottom engine will
gain automatic relegation. Any other changes of division will be at my
discretion and may not necessarily involve playoff matches.*

*Participants*

Drofa 3.3.22 64-bit
RukChess 3.0 64-bit
Dark Toga 1.1 64-bit (relegated)
Winter 1.0 64-bit
Orion 0.9 64-bit
Demolito 2021-10-04 64-bit (relegated)
Roc 1.9.1 64-bit
Invictus r382 64-bit
Mr Bob 1.1.0 64-bit
Viridithas 5.1.0 64-bit (promoted)
Sturddle 1.04 64-bit (new)
Frozenight 5.1.0 64-bit (promoted)


Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16091
